name: Go
on: [push]
jobs:
  protos-check:
    name: Build
    runs-on: ubuntu-latest
    container: bufbuild/buf
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          ref: master
      - name: Lint
        run: buf check lint --input-config protos/local/buf.yaml
      - name: Breaking changes
        run: buf check breaking --against-input .git#branch=master --input-config protos/local/buf.yaml
  generate:
    name: Regenerate files
    runs-on: ubuntu-latest
    container: 
      image: apssouza/proto-api-manager
      env:
        PROTOBUF_VERSION: 3.12.0
    steps:
    - name: Check out code
      uses: actions/checkout@v1
#    - name: Download protoc
#      run: >
#        apt-get update &&
#        apt-get install -y unzip &&
#        wget https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOBUF_VERSION/protoc-$PROTOBUF_VERSION-linux-x86_64.zip &&
#        unzip protoc-$PROTOBUF_VERSION-linux-x86_64.zip -d /usr/local/ &&
#        rm -rf protoc-$PROTOBUF_VERSION-linux-x86_64.zip
    - name: Regenerate files
      run: make generate
    - name: Check for a diff
      run: git diff --exit-code
